/**
 * `docs/coverage.md` must match what `criterion-coverage.ts` says today.
 *
 * The page is the reading copy of a fact that lives in code. Generating it removes the drift a hand-written
 * page would have — but only if something checks that it was regenerated, otherwise the generator is just a
 * convenience and the file goes stale exactly like a hand-written one would.
 *
 * That is not hypothetical here. `screenreader-coverage.md`'s own header says "a behaviour missing from
 * that table is not a missing feature; it is a claim this project cannot currently make" — and four
 * criteria were driven for a day before anyone added them to it.
 *
 * So: regenerate into a temporary file and diff. If this fails, run `npm run docs:coverage` and commit the
 * result — the page is wrong, not the test.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, mkdtempSync, cpSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { resolve, join } from "node:path";

const REPO = resolve(import.meta.dirname, "../../..");
const PAGE = resolve(REPO, "docs/coverage.md");

test("docs/coverage.md exists and is marked as generated", () => {
  assert.ok(existsSync(PAGE), "run `npm run docs:coverage`");
  assert.match(readFileSync(PAGE, "utf8"), /GENERATED by `npm run docs:coverage`/,
    "the page must say it is generated, or somebody will edit it by hand and lose the edit");
});

test("the committed page is what the generator produces today", () => {
  const before = readFileSync(PAGE, "utf8");
  // Regenerate into a COPY of the repo's docs dir? No — the generator writes to a fixed path by design, so
  // back the file up, regenerate in place, compare, restore. Cheap, and it exercises the real code path
  // rather than a parallel one that could diverge from it.
  const backup = join(mkdtempSync(join(tmpdir(), "coverage-doc-")), "coverage.md");
  cpSync(PAGE, backup);
  try {
    execFileSync("npx", ["tsx", "packages/lab/scripts/generate-coverage-doc.ts"],
      { cwd: REPO, encoding: "utf8", stdio: "pipe" });
    const after = readFileSync(PAGE, "utf8");
    assert.equal(after, before,
      "docs/coverage.md is out of date with criterion-coverage.ts — run `npm run docs:coverage` and commit");
  } finally {
    cpSync(backup, PAGE);
  }
});

test("the page states a count, and the count is not zero", () => {
  // The vacuity guard. A generator that silently produced an empty table would pass the diff above, because
  // the committed file would be empty too.
  const page = readFileSync(PAGE, "utf8");
  const assessed = /\*\*assessed\*\* \| (\d+) \|/.exec(page);
  assert.ok(assessed && Number(assessed[1]) > 0, "the page claims zero assessed criteria");
  assert.ok(page.split("\n").filter((l) => l.startsWith("| **")).length >= 10,
    "fewer than ten criterion rows — the generator produced almost nothing");
});
